### ISSUE TITLE
Display asset price in wallet 

### ISSUE THREAD

**Issue by MaudSimon** [alephium/alephium-frontend#161] opened 2023-12-07 18:45 UTC
**Is your feature request related to a problem? Please describe.**
It would be convenient to know the individual price for an asset (not just the portfolio value of said asset). 

**Describe the solution you'd like**
Display the price of the asset. 

**Describe alternatives you've considered**
Divide the portfolio value by the number of said asset I own)

**Additional context**
Community request I'm passing on.

**Comment by nop33** [comment] 2023-12-10 23:37
Duplicate of https://github.com/alephium/alephium-frontend/issues/88.

Closing.

**Closed by nop33** 2023-12-10 23:37 UTC
