### ISSUE TITLE
Error while re-order words in Mnemonic check

### ISSUE THREAD

**Issue by nit27** [alephium/alephium-frontend#640] opened 2024-06-10 03:08 UTC
**Describe the bug**
Words are dancing while re-ordering by dragging them :)

**To Reproduce**
In mnemonic check (after create a new wallet), click to choose the order of mnemonic. Drag words to re-order causes error.

**Screenshots**
<img width="1312" alt="Screenshot 2024-06-10 at 09 59 44" src="https://github.com/alephium/alephium-frontend/assets/95131051/ed08e48b-f545-4511-ac9a-f98fbb2a0af7">

**Environment**
- Desktop wallet: v2.3.3
- OS: MacOS
- Version: Ventura 13.6.7

**Comment by nop33** [comment] 2024-06-10 05:53
Thanks for the report @nit27! This issue is a duplicate of https://github.com/alephium/alephium-frontend/issues/553. We will address this issue when we work on https://github.com/alephium/alephium-frontend/issues/39. Closing issue.

**Closed by nop33** 2024-06-10 05:53 UTC
