### ISSUE TITLE
Black screen on wallet creation on iOS

### ISSUE THREAD

**Issue by mvaivre** [alephium/alephium-frontend#750] opened 2024-07-26 08:08 UTC
User created a wallet successfully. On second app launch, screen is black with no error.
User reinstalled the app, imported the wallet they created before, same black screen.

- iOS 15.5.1 (21F90)
- iPhone 12

**Comment by nop33** [comment] 2024-08-08 11:45
Duplicate of https://github.com/alephium/alephium-frontend/issues/690

**Comment by nop33** [comment] 2024-08-14 11:13
Now that the 1.1.3 is live on the AppStore, I asked the user who reported this to check if it fixes the problem.

**Comment by nop33** [comment] 2024-08-31 08:01
User confirmed that the problem is resolved. Closing issue.

**Closed by nop33** 2024-08-31 08:01 UTC
Labels: bug, 📱 MW
