### ISSUE TITLE
Message signing support

### ISSUE THREAD

**Issue by polarker** [alephium/alephium-frontend#280] opened 2024-01-17 14:22 UTC
**Is your feature request related to a problem? Please describe.**
Allowing dapp to sign messages for authentication. Currently the extension wallet support the feature

**Describe the solution you'd like**
You could try to feature here: https://alephium.github.io/extension-wallet/

**Comment by nop33** [comment] 2024-01-18 00:03
Is this a duplicate of https://github.com/alephium/alephium-frontend/issues/34?

**Comment by nop33** [comment] 2024-01-18 02:48
Closing as duplicate of #34. I'll work on #34 now.

**Closed by nop33** 2024-01-18 02:48 UTC
